[package]
name = "ousject-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ousject"
path = "src/main.rs"

[dependencies]
oms-runtime = { path = "../oms-runtime" }
oms-types = { path = "../oms-types" }
ousject-vm = { path = "../ousject-vm" }
ousject-auth = { path = "../ousject-auth" }
ousject-provider = { path = "../ousject-provider" }
praxis-compiler = { path = "../praxis-compiler" }
tf-format = { path = "../tf-format" }
nix = { version = "0.30", features = ["term"] }

[lints]
workspace = true
