[package]
name = "ousject-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
oms-runtime = { path = "../oms-runtime" }
oms-types = { path = "../oms-types" }
ousject-provider = { path = "../ousject-provider" }
ousject-auth = { path = "../ousject-auth" }
praxis-compiler = { path = "../praxis-compiler" }
tf-format = { path = "../tf-format" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2.12"

[lints]
workspace = true
